services:
  fastsam-api:
    container_name: fastsam-api
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
    platform: linux/amd64
    pull_policy: always
    ports:
      - 8021:8000
    env_file:
      - .env
    volumes:
      - ../assets/:/app/assets
